import React, { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { preview } from "../assets"
import { getRandomPrompt } from "../utils"
import { FormField, Loader } from "../components"

const CreatePost = () => {

  const navigate = useNavigate() // this will aloow us to navigate back to the home page , once the post has been created..

  const [form, setForm] = useState({
    name: '',
    prompt: '',
    content: '',
    photo: '',
  })

  const [generatingImg, setGeneratingImg] = useState(false) // we will use this while , we will be making contact to out api ..
  const [loading, setLoading] = useState(false) // upto this state , these were the all states we needed to make the createPost Page 

  const handleSurpriseMe = () => {
    const randomPrompt = getRandomPrompt(form.prompt)
    setForm({ ...form, prompt: randomPrompt })
  }

  const handleSubmit = (e) => {
    e.preventDefault()
    //will do something here 
    if (!form.prompt || !form.photo) return
    navigate("/")
  }

  const handleChange = (e) => {
    //e stands for event 
    setForm({ ...form, [e.target.name]: e.target.value })
  }

  const generateImage = () => {
    setGeneratingImg(true)
    setTimeout(() => {
      setForm({ ...form, photo: preview })
      setGeneratingImg(false)
    }, 1500)
  }

  return (
    <section className="max-w-7xl mx-auto px-4 py-10">
      <div className="mb-10">
        <h1 className="font-extrabold text-white text-[36px]">
          Create
        </h1>
        <p className="mt-2 text-gray-400 text-[16px] max-w-[520px]">
          Create most visually stunning images , generated by QuickPicAI and share them with the Community...
        </p>
      </div>

      <form
        className="bg-[#0b0b14] border border-[#1f1f2e] rounded-2xl p-8 max-w-3xl"
        onSubmit={handleSubmit}
      >
        <div className="flex flex-col gap-6">

          <FormField
            LabelName="Your Name"
            name="name"
            type="text"
            placeholder="Enter your name"
            value={form.name}
            handleChange={handleChange}
          />

          <FormField
            LabelName="Prompt"
            name="prompt"
            type="text"
            placeholder="teddy bears shopping for groceries in Japan, ukiyo-e"
            value={form.prompt}
            handleChange={handleChange}
            isSurpriseMe
            handleSurpriseMe={handleSurpriseMe}
          />

          <div className="relative w-full h-72 rounded-xl bg-[#111827] border border-[#1f2937] flex justify-center items-center overflow-hidden">
            {form.photo ? (
              <img
                src={form.photo}
                alt={form.prompt}
                className="w-full h-full object-contain"
              />
            ) : (
              <img
                src={preview}
                alt="preview"
                className="w-2/3 opacity-30"
              />
            )}

            {generatingImg && (
              <div className="absolute inset-0 bg-black/60 flex items-center justify-center">
                <Loader />
              </div>
            )}
          </div>

          <button
            type="button"
            onClick={generateImage}
            className="w-full py-3 rounded-xl font-semibold text-white
                       bg-gradient-to-r from-green-500 to-emerald-600
                       hover:opacity-90 transition"
          >
            {generatingImg ? 'Generating…' : 'Generate Image'}
          </button>
        </div>

        <div className="mt-8">
          <p className="text-sm text-gray-400">
            Once you have created the image, you can share it with others in the community
          </p>
          <button
            type="submit"
            className="mt-4 w-full py-3 rounded-xl font-semibold text-white
                       bg-gradient-to-r from-indigo-500 to-purple-600
                       hover:opacity-90 transition"
          >
            {loading ? 'Sharing…' : 'Share with the community'}
          </button>
        </div>
      </form>
    </section>
  )
}

export default CreatePost
