import React, { useState } from 'react'
import { Loader, Card, FormField } from '../components'

const RenderCards = ({ data, title }) => {
  if (data?.length > 0) {
    return data.map((post) => <Card key={post._id} {...post} />)
  }

  return (
    <h2 className="mt-10 text-center font-semibold text-gray-400 text-xl">
      {title}
    </h2>
  )
}

const Home = () => {
  const [loading, setLoading] = useState(false)
  const [allPosts, setAllPosts] = useState([])
  const [searchText, setSearchText] = useState('')

  return (
    <section className="max-w-7xl mx-auto px-4 py-10">
      <div>
        <h1 className="font-extrabold text-white text-[36px]">
          The QuickPic Showcase
        </h1>
        <p className="mt-2 text-gray-400 text-[16px] max-w-[520px]">
          Take a look at visually stunning images , generated by QuickPicAI
        </p>
      </div>

      <div className="mt-12">
        <FormField
          LabelName="Search"
          type="text"
          name="search"
          placeholder="Search something amazing..."
          value={searchText}
          handleChange={(e) => setSearchText(e.target.value)}
        />
      </div>

      <div className="mt-12">
        {loading ? (
          <div className="flex justify-center items-center">
            <Loader />
          </div>
        ) : (
          <>
            {searchText && (
              <h2 className="font-medium text-gray-400 text-xl mb-6">
                Showing results for{" "}
                <span className="text-white">{searchText}</span>
              </h2>
            )}

            <div className="grid gap-6 lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1">
              <RenderCards
                data={allPosts}
                title={searchText ? "No results found" : "No posts yet"}
              />
            </div>
          </>
        )}
      </div>
    </section>
  )
}

export default Home
